### ISSUE TITLE
No Audio Debian 12 Samsung Galaxy 2 Chromebook

### ISSUE THREAD

**Issue by ThePizzaTimeBandit** [WeirdTreeThing/chromebook-linux-audio#14]
I don't have any audio output after running this script on a debian 12 chromebook.  This is being run with MrChromeBox's UEFI firmware.  Kernel version is 6.1.0-10-amd64.  aplay -l list no soundcards.

**Comment by WeirdTreeThing** [comment]
Download [this deb](https://elly.rocks/tmp/BUILDROOT/linux-image-6.1.27chrultrabook-fixups_6.1.27chrultrabook-fixups-8_amd64.deb) and install it with apt.

**Comment by ThePizzaTimeBandit** [comment]
Sound cards are now detecting in aplay -l

**** List of PLAYBACK Hardware Devices ****
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 0: Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 5: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 6: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 7: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

However, in the audio console I am still unable to enable the device in kde plasma.

**Comment by WeirdTreeThing** [comment]
I need to add UCM for nightfury.

**Comment by WeirdTreeThing** [comment]
UCM has been added, run the script again.

**Comment by ThePizzaTimeBandit** [comment]
I reran the script, the issue still persists.  I did a fresh install in case there was a change that I made that didn't jive right.  This issue persists after the reinstall

**Comment by WeirdTreeThing** [comment]
Send the output of `strace alsaucm reload &> alsaucm.txt`

**Comment by WeirdTreeThing** [comment]
Have a look at the pinned issue in this repo.

**Comment by ThePizzaTimeBandit** [comment]
execve("/usr/bin/alsaucm", ["alsaucm", "reload"], 0x7ffc7c2575b8 /* 41 vars */) = 0
brk(NULL)                               = 0x555d92b54000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f63ee8b8000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=69554, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 69554, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f63ee8a7000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libasound.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1079888, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 1082736, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f63ee79e000
mmap(0x7f63ee7cc000, 614400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2e000) = 0x7f63ee7cc000
mmap(0x7f63ee862000, 245760, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc4000) = 0x7f63ee862000
mmap(0x7f63ee89e000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xff000) = 0x7f63ee89e000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220s\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1922136, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1970000, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f63ee5bd000
mmap(0x7f63ee5e3000, 1396736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f63ee5e3000
mmap(0x7f63ee738000, 339968, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17b000) = 0x7f63ee738000
mmap(0x7f63ee78b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ce000) = 0x7f63ee78b000
mmap(0x7f63ee791000, 53072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f63ee791000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=907784, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 909560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f63ee4de000
mmap(0x7f63ee4ee000, 471040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7f63ee4ee000
mmap(0x7f63ee561000, 368640, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x83000) = 0x7f63ee561000
mmap(0x7f63ee5bb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xdc000) = 0x7f63ee5bb000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f63ee4dc000
arch_prctl(ARCH_SET_FS, 0x7f63ee4dcb80) = 0
set_tid_address(0x7f63ee4dce50)         = 3354
set_robust_list(0x7f63ee4dce60, 24)     = 0
rseq(0x7f63ee4dd4a0, 0x20, 0, 0x53053053) = 0
mprotect(0x7f63ee78b000, 16384, PROT_READ) = 0
mprotect(0x7f63ee5bb000, 4096, PROT_READ) = 0
mprotect(0x7f63ee89e000, 32768, PROT_READ) = 0
mprotect(0x555d9159d000, 4096, PROT_READ) = 0
mprotect(0x7f63ee8ea000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f63ee8a7000, 69554)           = 0
getrandom("\xa1\xd7\x8f\x7c\x5f\x33\xab\x6e", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x555d92b54000
brk(0x555d92b75000)                     = 0x555d92b75000
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffeb15ec240) = 0
close(3)                                = 0
futex(0x7f63ee8a6260, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(AT_FDCWD, "/usr/share/alsa/alsa.conf", {st_mode=S_IFREG|0644, st_size=10117, ...}, 0) = 0
openat(AT_FDCWD, "/usr/share/alsa/alsa.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=10117, ...}, AT_EMPTY_PATH) = 0
read(3, "#\n#  ALSA library configuration "..., 4096) = 4096
read(3, "hint.extended\n\t\t}\n\t\tdescription "..., 4096) = 4096
read(3, "e\n#\n\nhwdep.default {\n\ttype hw\n\tc"..., 4096) = 1925
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/var/lib/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/etc/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/etc/alsa/conf.d", R_OK)        = 0
newfstatat(AT_FDCWD, "/etc/alsa/conf.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/alsa/conf.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
getdents64(3, 0x555d92b668e0 /* 4 entries */, 32768) = 136
getdents64(3, 0x555d92b668e0 /* 0 entries */, 32768) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-pipewire.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1842, ...}, AT_EMPTY_PATH) = 0
read(3, "# Add a specific named PipeWire "..., 4096) = 1842
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/99-pipewire-default.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=226, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.!default {\n    type pipewire"..., 4096) = 226
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/etc/asound.conf", R_OK)        = -1 ENOENT (No such file or directory)
access("/usr/etc/asound.conf", R_OK)    = -1 ENOENT (No such file or directory)
access("/home/thomas/.asoundrc", R_OK)  = -1 ENOENT (No such file or directory)
access("/home/thomas/.config/alsa/asoundrc", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffeb15ebc20) = 0
close(3)                                = 0
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDWR|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_PVERSION, 0x7ffeb15ebff4) = 0
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffeb15ec1b0) = 0
access("/usr/share/alsa/ucm2/ucm.conf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/ucm.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=3599, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is the toplevel file in"..., 4096) = 3599
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/lib/generic.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=452, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is generic UCM configur"..., 4096) = 452
read(4, "", 4096)                       = 0
close(4)                                = 0
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/Google-Nightfury-rev7.conf", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", R_OK) = -1 ENOENT (No such file or directory)
close(3)                                = 0
write(2, "ALSA lib main.c:1541:(snd_use_ca"..., 45ALSA lib main.c:1541:(snd_use_case_mgr_open) ) = 45
write(2, "error: failed to import hw:0 use"..., 54error: failed to import hw:0 use case configuration -2) = 54
write(2, "\n", 1
)                       = 1
write(2, "alsaucm: error failed to open so"..., 73alsaucm: error failed to open sound card hw:0: No such file or directory
) = 73
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by WeirdTreeThing** [comment]
It seems like you either didn't run the script or it somehow didn't copy the UCM.

**Comment by WeirdTreeThing** [comment]
My bad, it was an issue with the script. `git pull` and try again.

**Comment by ThePizzaTimeBandit** [comment]
I am still only showing dummy output but I reran strace and have different results.

execve("/usr/bin/alsaucm", ["alsaucm", "reload"], 0x7ffd9fd1c1f8 /* 41 vars */) = 0
brk(NULL)                               = 0x56098d6a5000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7febc0b12000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=69554, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 69554, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7febc0b01000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libasound.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1079888, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 1082736, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7febc09f8000
mmap(0x7febc0a26000, 614400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2e000) = 0x7febc0a26000
mmap(0x7febc0abc000, 245760, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc4000) = 0x7febc0abc000
mmap(0x7febc0af8000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xff000) = 0x7febc0af8000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220s\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1922136, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1970000, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7febc0817000
mmap(0x7febc083d000, 1396736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7febc083d000
mmap(0x7febc0992000, 339968, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17b000) = 0x7febc0992000
mmap(0x7febc09e5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ce000) = 0x7febc09e5000
mmap(0x7febc09eb000, 53072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7febc09eb000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=907784, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 909560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7febc0738000
mmap(0x7febc0748000, 471040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7febc0748000
mmap(0x7febc07bb000, 368640, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x83000) = 0x7febc07bb000
mmap(0x7febc0815000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xdc000) = 0x7febc0815000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7febc0736000
arch_prctl(ARCH_SET_FS, 0x7febc0736b80) = 0
set_tid_address(0x7febc0736e50)         = 2775
set_robust_list(0x7febc0736e60, 24)     = 0
rseq(0x7febc07374a0, 0x20, 0, 0x53053053) = 0
mprotect(0x7febc09e5000, 16384, PROT_READ) = 0
mprotect(0x7febc0815000, 4096, PROT_READ) = 0
mprotect(0x7febc0af8000, 32768, PROT_READ) = 0
mprotect(0x56098bd1d000, 4096, PROT_READ) = 0
mprotect(0x7febc0b44000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7febc0b01000, 69554)           = 0
getrandom("\x8e\x6c\xf7\xb9\x30\x73\x19\xb7", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x56098d6a5000
brk(0x56098d6c6000)                     = 0x56098d6c6000
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffe039a1370) = 0
close(3)                                = 0
futex(0x7febc0b00260, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(AT_FDCWD, "/usr/share/alsa/alsa.conf", {st_mode=S_IFREG|0644, st_size=10117, ...}, 0) = 0
openat(AT_FDCWD, "/usr/share/alsa/alsa.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=10117, ...}, AT_EMPTY_PATH) = 0
read(3, "#\n#  ALSA library configuration "..., 4096) = 4096
read(3, "hint.extended\n\t\t}\n\t\tdescription "..., 4096) = 4096
read(3, "e\n#\n\nhwdep.default {\n\ttype hw\n\tc"..., 4096) = 1925
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/var/lib/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/etc/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/etc/alsa/conf.d", R_OK)        = 0
newfstatat(AT_FDCWD, "/etc/alsa/conf.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/alsa/conf.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
getdents64(3, 0x56098d6b78e0 /* 4 entries */, 32768) = 136
getdents64(3, 0x56098d6b78e0 /* 0 entries */, 32768) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-pipewire.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1842, ...}, AT_EMPTY_PATH) = 0
read(3, "# Add a specific named PipeWire "..., 4096) = 1842
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/99-pipewire-default.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=226, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.!default {\n    type pipewire"..., 4096) = 226
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/etc/asound.conf", R_OK)        = -1 ENOENT (No such file or directory)
access("/usr/etc/asound.conf", R_OK)    = -1 ENOENT (No such file or directory)
access("/home/thomas/.asoundrc", R_OK)  = -1 ENOENT (No such file or directory)
access("/home/thomas/.config/alsa/asoundrc", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffe039a0d50) = 0
close(3)                                = 0
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDWR|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_PVERSION, 0x7ffe039a1124) = 0
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffe039a12e0) = 0
access("/usr/share/alsa/ucm2/ucm.conf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/ucm.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=3599, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is the toplevel file in"..., 4096) = 3599
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/lib/generic.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=452, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is generic UCM configur"..., 4096) = 452
read(4, "", 4096)                       = 0
close(4)                                = 0
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/Google-Nightfury-rev7.conf", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", R_OK) = 0
newfstatat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", {st_mode=S_IFREG|0644, st_size=122, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=122, ...}, AT_EMPTY_PATH) = 0
read(4, "Syntax 6\n\nComment \"sof-cml_max98"..., 4096) = 122
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/HiFi.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=3077, ...}, AT_EMPTY_PATH) = 0
read(4, "SectionVerb {\n\tValue {\n\t\tFullySp"..., 4096) = 3077
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/dmic-common/split.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=8594, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Split multichannel PCM strea"..., 4096) = 4096
brk(0x56098d6e7000)                     = 0x56098d6e7000
read(4, "ap [ \"${var:-__HWChannelPos12}\" "..., 4096) = 4096
read(4, "\" \"${var:__ChannelPos1}\"\n\t\t\t\t}\n\t"..., 4096) = 402
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/dmic-common/remap.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=1071, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Remap controls\n#\n\n#\n# Macro "..., 4096) = 1071
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/hdmi-common/hdmi567.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=400, ...}, AT_EMPTY_PATH) = 0
read(4, "# HDA HDMI devices\n\nInclude.hdmi"..., 4096) = 400
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/hdmi-common/hdmi.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=732, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Macro HDMI\n#\n# Arguments:\n#\n"..., 4096) = 732
read(4, "", 4096)                       = 0
close(4)                                = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a0880) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a0880) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a0880) = 0
write(2, "ALSA lib ucm_subs.c:799:(uc_mgr_"..., 55ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) ) = 55
write(2, "variable '${var:__Src}' is not d"..., 55variable '${var:__Src}' is not defined in this context!) = 55
write(2, "\n", 1
)                       = 1
write(2, "ALSA lib ucm_subs.c:799:(uc_mgr_"..., 55ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) ) = 55
write(2, "variable '${var:__Src}' is not d"..., 55variable '${var:__Src}' is not defined in this context!) = 55
write(2, "\n", 1
)                       = 1
access("/usr/share/alsa/ucm2/ucm.conf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/ucm.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=3599, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is the toplevel file in"..., 4096) = 3599
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/lib/generic.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=452, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# This is generic UCM configur"..., 4096) = 452
read(4, "", 4096)                       = 0
close(4)                                = 0
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/Google-Nightfury-rev7.conf", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", R_OK) = 0
newfstatat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", {st_mode=S_IFREG|0644, st_size=122, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/sof-cml_max9839.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=122, ...}, AT_EMPTY_PATH) = 0
read(4, "Syntax 6\n\nComment \"sof-cml_max98"..., 4096) = 122
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/HiFi.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=3077, ...}, AT_EMPTY_PATH) = 0
read(4, "SectionVerb {\n\tValue {\n\t\tFullySp"..., 4096) = 3077
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/dmic-common/split.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=8594, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Split multichannel PCM strea"..., 4096) = 4096
read(4, "ap [ \"${var:-__HWChannelPos12}\" "..., 4096) = 4096
read(4, "\" \"${var:__ChannelPos1}\"\n\t\t\t\t}\n\t"..., 4096) = 402
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/dmic-common/remap.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=1071, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Remap controls\n#\n\n#\n# Macro "..., 4096) = 1071
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/hdmi-common/hdmi567.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=400, ...}, AT_EMPTY_PATH) = 0
read(4, "# HDA HDMI devices\n\nInclude.hdmi"..., 4096) = 400
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/conf.d/hdmi-common/hdmi.conf", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=732, ...}, AT_EMPTY_PATH) = 0
read(4, "#\n# Macro HDMI\n#\n# Arguments:\n#\n"..., 4096) = 732
read(4, "", 4096)                       = 0
close(4)                                = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a08c0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a08c0) = 0
ioctl(3, SNDRV_CTL_IOCTL_ELEM_INFO, 0x7ffe039a08c0) = 0
write(2, "ALSA lib ucm_subs.c:799:(uc_mgr_"..., 55ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) ) = 55
write(2, "variable '${var:__Src}' is not d"..., 55variable '${var:__Src}' is not defined in this context!) = 55
write(2, "\n", 1
)                       = 1
write(2, "ALSA lib ucm_subs.c:799:(uc_mgr_"..., 55ALSA lib ucm_subs.c:799:(uc_mgr_get_substituted_value) ) = 55
write(2, "variable '${var:__Src}' is not d"..., 55variable '${var:__Src}' is not defined in this context!) = 55
write(2, "\n", 1
)                       = 1
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by WeirdTreeThing** [comment]
Run this [script](https://cdn.discordapp.com/attachments/1121994891950559283/1126689828063412234/audio-debug.sh) and upload the output file.

**Comment by ThePizzaTimeBandit** [comment]
[audio-debug.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12286895/audio-debug.log)

**Comment by WeirdTreeThing** [comment]
Send dmesg.

**Comment by ThePizzaTimeBandit** [comment]
Here is the dmesg;

[dmesg.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12287103/dmesg.txt)

**Comment by ThePizzaTimeBandit** [comment]
So this was a little different than that.  My audio is now working.  The pipewire and pulseaudio services were hosed and weren't starting.  I now have front audio through pipewire with pulseaudio going to /dev/null.  

I am still having an issue with my 3.5mm jack, but I can create a separate issue if you like.

**Comment by WeirdTreeThing** [comment]
What is wrong with it?

**Comment by ThePizzaTimeBandit** [comment]
Sorry for my delay.  It doesn't appear to be working at all.

**Comment by WeirdTreeThing** [comment]
Does it get detected when you plug it in?

**Comment by ThePizzaTimeBandit** [comment]
No, it doesn't detect it.

**Comment by WeirdTreeThing** [comment]
Run `alsactl monitor`, plug in your headphones, check for any output.

**Comment by ThePizzaTimeBandit** [comment]
Sorry for my delay, here is the output.  
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE
node hw:0, #87 (0,0,0,Headphone Jack,0) VALUE
node hw:0, #88 (0,0,0,Headset Mic Jack,0) VALUE

**Comment by WeirdTreeThing** [comment]
Strange, it looks like the driver is broken. As a workaround, edit `/usr/share/alsa/ucm2/conf.d/sof-cml_max9839/HiFi.conf` and delete lines 99 and 139.

**Comment by WeirdTreeThing** [comment]
Also, you should be able to use pipewire.

**Comment by MetalfaceScout** [comment]
I have what I assume is the same issue, I don't have an audio profile show up in GNOME. 
[Here's the audio debug log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13057050/audio-debug.log)

**Comment by WeirdTreeThing** [comment]
You posted a log for Magpie on the Nightfury issue?

**Comment by MetalfaceScout** [comment]
Oops, I did. I downloaded a few of them when I was trying to troubleshoot it myself, here's my log.
[audio-debug.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13168586/audio-debug.log)

**Comment by WeirdTreeThing** [comment]
Send output of `aplay -l`, `arecord -l`, and `dmesg`.

**Comment by MetalfaceScout** [comment]
`aplay -l`
```
**** List of PLAYBACK Hardware Devices ****
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 0: Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 5: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 6: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 7: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
`arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 2: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 4: EchoRef (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofcmlmax98390d [sof-cml_max98390_da7219], device 8: DMIC16k (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
[dmesg.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13169021/dmesg.log)

**Comment by WeirdTreeThing** [comment]
I pushed a ucm update, run the script and try again.

**Comment by MetalfaceScout** [comment]
That did it for the speakers, the profile shows now. I don't have any output on the left speaker. I'll test the headphone jack as soon as I have access to some headphones.

**Comment by MetalfaceScout** [comment]
The profile is gone again, my `aplay -l` and `arecord -l` are the same as before.
Here's the logs:
[audio-debug.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13182878/audio-debug.log)
[dmesg.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13182879/dmesg.log)

**Comment by MetalfaceScout** [comment]
I just tested the headphone jack with the master branch of the ucm conf, and it works flawlessly. The only problem with the config in the master branch is the front left speaker doesn't work, at least for me. The nightfury branch is still broken.

**Comment by WeirdTreeThing** [comment]
Can you open alsamixer, press s to switch to sof-cml.... card, then play around with mixer settings (arrow keys to move around, up and down to change volume levels, m to toggle mute) and let me know if changing one fixes the left speaker.

**Comment by MetalfaceScout** [comment]
I did that, and it didn't seem to do anything. So I pulled it apart and turns out the connector for the left speaker was broken off somehow. I fixed it and now it's working. The left speaker is significantly louder though, does the alsamixer stuff reset after every reboot?

**Comment by WeirdTreeThing** [comment]
Oh lol, that will do it. You can email me at weirdtreething@chrultrabook.com for donations.
